### ISSUE TITLE
Can't create uninstaller on Windows 7 x64

### ISSUE THREAD

**Issue by dev0tion** [stratisproject/FullNodeUI#17]
From @sigma in Slack:
<img width="431" alt="screen shot 2017-12-18 at 16 57 57" src="https://user-images.githubusercontent.com/10409230/34115425-e2688e5c-e415-11e7-87b6-08dc07b59aca.png">

**Comment by bokobza** [comment]
Tested with Windows 7 x86 ad x64 and it's ok.
I'll check with Sigma if this is still relevant.

**Comment by bokobza** [comment]
Sigma reports it's not an issue anymore. Closing.
