### ISSUE TITLE
Transactions not propagating

### ISSUE THREAD

**Issue by D3m0nKingx** [stratisproject/FullNodeUI#19]
![screenshot from 2017-12-19 05-35-25](https://user-images.githubusercontent.com/18432686/34153017-898d121c-e47e-11e7-9a48-ecf1a9627676.png)
 
I attempted to recombine the full wallet balance, the transaction still in "unconfirmed" status.

I tested this with @Daandamhuis, he sent me some testnet coins, which I received (2.9 and 0.9 TSTRATS) and confirmed (as seen in the screenshot), however when I attempted to send some back the tx didn't propagate, staying in unconfirmed status, and Daan reported nothing appeared in his wallet from my tx.

**Comment by Daandamhuis** [comment]
Here it is form my side: 
![stratis - wallet - errror](https://user-images.githubusercontent.com/3600611/34155045-1ef6ac9e-e4b8-11e7-9863-68a89cc512e5.png)

**Comment by Daandamhuis** [comment]
I think this could be related to this: 
https://github.com/stratisproject/StratisBitcoinFullNode/issues/952

**Comment by D3m0nKingx** [comment]
Referencing Bug: [#957](https://github.com/stratisproject/StratisBitcoinFullNode/issues/957)

**Comment by bokobza** [comment]
fixed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/1036
