### ISSUE TITLE
Feedback from Slack user @tombo

### ISSUE THREAD

**Issue by dev0tion** [stratisproject/FullNodeUI#21]
[feedback-wallet.pdf](https://github.com/stratisproject/FullNodeUI/files/1575791/feedback-wallet.pdf)

**Comment by bep42** [comment]
Did we not checked the feedbacks already?

**Comment by bep42** [comment]
to my side, we can close this issue

**Comment by dev0tion** [comment]
Yes, we discussed and done these points.
