### ISSUE TITLE
Error while sending a transaction

### ISSUE THREAD

**Issue by noescape00** [stratisproject/FullNodeUI#24]
This happened to me when I was sending a tx that combined a lot of inputs. 
Let's say we have 8 peers and propagate the tx to them one by one and on 6th peer it disconnects. The wallet will show an error: 
![err](https://user-images.githubusercontent.com/10259355/35485887-b8b3730c-0476-11e8-9f8e-461193ce57f5.png)

But the tx was propagated properly.
Because of this error user might get an Idea that tx was not sent which is wrong.

**Comment by dev0tion** [comment]
@bokobza is this still an issue with the current submodule?

**Comment by noescape00** [comment]
I think it's not an issue anymore. 

This error is being thrown from NetworkPeer.SendMessageAsync and it looks like now in the BroadcasterManagerBase there is a try catch block which prevents this from stopping the propagation foreach: 

```
foreach (INetworkPeer peer in peers)
{
    try
    {
        await peer.SendMessageAsync(invPayload).ConfigureAwait(false);
    }
    catch (OperationCanceledException)
    {
    }
}
```

**Comment by dev0tion** [comment]
Thanks @noescape00 
Closing for now.
