### ISSUE TITLE
Wallet restore error

### ISSUE THREAD

**Issue by noescape00** [stratisproject/FullNodeUI#25]
When I try to restore the wallet it says that wallet under that name already exists when in fact there is no wallet.json file in the folder

![err](https://user-images.githubusercontent.com/10259355/35486244-3081b100-047c-11e8-9b7d-04fe6b328e88.png)

If I try to restore wallet under a different name it says: 

`Cannot create this wallet as a wallet with the same private key already exists. If you want to restore your wallet from scratch, please remove the file testWallet, testWallet.wallet.json from 'C:\Users\user\AppData\Roaming\StratisNode\stratis\StratisTest' and try restoring the wallet again. Make sure you have your mnemonic and your password handy!`

The thing is that after I press the "Restore" button for the first time it launches the restore process but at the same time it spawns the error (which is wrong). If I keep the app open long enough the wallet file eventually get created.

**Comment by D3m0nKingx** [comment]
@noescape00 be aware the FullNode Submodule isn't updated either. I just ran it independently from the UI, and it has the issue you and I had determined was causing a problem with peer threads usage delay on [#1058](https://github.com/stratisproject/StratisBitcoinFullNode/pull/1058)

**Comment by noescape00** [comment]
@D3m0nKingx yeah, I know. I think this is UI problem and this error should not be spawned.

**Comment by D3m0nKingx** [comment]
Try running the UI in development mode, so you can use the Developer Tools ( Ctrl+shift I )

**Comment by D3m0nKingx** [comment]
I just attempted the restore, Doesn't work at all for me, cause the Stratis Daemon isn't responding, and Swagger doesn't even load in the browser.

**Comment by D3m0nKingx** [comment]
I see in the console:

>Request URL:http://localhost:37221/api/wallet/files
Referrer Policy:no-referrer-when-downgrade

![screenshot from 2018-01-28 15-56-24](https://user-images.githubusercontent.com/18432686/35486966-efde2684-0443-11e8-8d42-d4428956832c.png)

**Comment by bokobza** [comment]
@D3m0nKingx @noescape00 The Full node now has 38221 as the port for Stratis Testnet.
So if you run the FN along with the non-updated FullNode.UI, it won't work.
Please wait for @dev0tion to update it or change all instances of 37221 to 38221 in the FullNode.UI front end code.

**Comment by dev0tion** [comment]
It's ok for me if you want to update the submodule @bokobza?
Then I will make adjustments to the UI.

**Comment by bokobza** [comment]
ok!

**Comment by dev0tion** [comment]
Fixed with the submodule update a while ago
