### ISSUE TITLE
Node daemon occasionally stays after Stratis Wallet is closed

### ISSUE THREAD

**Issue by noescape00** [stratisproject/FullNodeUI#26]
![err](https://user-images.githubusercontent.com/10259355/35562312-0619de12-05c4-11e8-86f2-ab760131f677.png)

**Comment by bokobza** [comment]
Duplicate of https://github.com/stratisproject/Breeze/issues/314
I'm actually working on this as we speak 😆

**Comment by noescape00** [comment]
Oh, didn't know. 
Awesome, @bokobza!
