### ISSUE TITLE
Calendar control doesn't render correctly for the date picker when restoring the wallet

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/FullNodeUI#38]
The calendar date picker doesn't have a background which makes the days difficult to read.
Platform: Windows 10

**Comment by dev0tion** [comment]
Hey @maciejzaleski, is this using the production executable or npm start?
It's rendering OK here. Have you checked with the latest code?

![image](https://user-images.githubusercontent.com/10409230/37962584-e22e3ba0-31bb-11e8-92c4-d7b9d1d5a86b.png)

**Comment by maciejzaleski** [comment]
The problem is only present in my set-up and will not be a problem in the released version.
