### ISSUE TITLE
Incorrect error message when sending large STRAT amount

### ISSUE THREAD

**Issue by maciejzaleski** [stratisproject/FullNodeUI#39]
When the amount is set to 100000000000 the error message shown incorrectly refers to bitcoin where it should say strat "Impossible to parse the string in a bitcoin amount"

**Comment by dev0tion** [comment]
@bokobza this error message comes from the backend, can you change it so it displays the current active coin? Cheers.

**Comment by bokobza** [comment]
on it.

**Comment by dev0tion** [comment]
Looks like the fix was merged, thanks @bokobza.
I'll leave this open until we've updated the submodule.

**Comment by dev0tion** [comment]
Closing cause submodule was updated
