### ISSUE TITLE
multiple accounts shown combined in history but not in balance

### ISSUE THREAD

**Issue by majikandy** [stratisproject/FullNodeUI#54]
Multiple Accounts not yet supported by the UI....  but there is an inconsistency.

UI only showing "account 0"

but with a wallet with "account 1" with transactions, the balance is shown for "account 0" but the history appears to show all transactions, including those that were made on "account 1" 

If the UI is only going to support account 0 then perhaps the history of other accounts shouldn't be shown (until there is full support for accounts.

**Comment by bokobza** [comment]
Leave it here, I'll take care of it soon.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dev0tion** [comment]
Fixed in #58
